.swiftlint.yml
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ContentView.swift
Sources/Amplitude/Amplitude.swift
Sources/Amplitude/Configuration.swift
Sources/Amplitude/Events/BaseEvent.swift
Sources/Amplitude/Events/GroupIdentifyEvent.swift
Sources/Amplitude/Events/Identify.swift
Sources/Amplitude/Events/IdentifyEvent.swift
Sources/Amplitude/Events/Revenue.swift
Sources/Amplitude/Events/RevenueEvent.swift
Sources/Amplitude/Plugins/ContextPlugin.swift
Sources/Amplitude/State.swift
Sources/Amplitude/Timeline.swift
Sources/Amplitude/TrackingOptions.swift
Sources/Amplitude/Types.swift
Sources/Amplitude/Utilities/CodableExtension.swift
Tests/AmplitudeTests/AmplitudeTests.swift
Tests/AmplitudeTests/Events/BaseEventTests.swift
Tests/AmplitudeTests/Events/GroupIdentifyEventTests.swift
Tests/AmplitudeTests/Events/IdentifyEventTests.swift
Tests/AmplitudeTests/Events/IdentifyTests.swift
Tests/AmplitudeTests/Events/RevenueEventTests.swift
Tests/AmplitudeTests/Events/RevenueTests.swift
Tests/AmplitudeTests/Supports/TestUtilities.swift

- feat: identify, revenue, amplitude client
- feat: remove idfa tracking config
This PR also includes changes:
- complete the example app with the real events
- add `@discardableResult` to public methods
- fix properties like `eventProperties` to be type `[String: Any?]?`, and add test cases
- fix special events like `IdentifyEvent` init issue with convenience init

feat: identify, revenue, amplitude client

---

Sources/Amplitude/Constants.swift
release.config.js

- build: add semantic release config

build: add semantic release config

---

release.config.js

- build: fix semantic release with regex match

build: fix semantic release with regex match

---

Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/IDFACollectionPlugin.swift
Sources/Amplitude/Plugins/ContextPlugin.swift

- feat: add carrier info
- doc: add comment to plugin example

feat: add carrier info

---

Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample.xcodeproj/project.pbxproj
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample.xcodeproj/xcshareddata/xcschemes/iOSWidgetExampleExtension.xcscheme
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/Info.plist
Examples/AmplitudeSwiftUIExample/iOSAppClip/Assets.xcassets/AccentColor.colorset/Contents.json
Examples/AmplitudeSwiftUIExample/iOSAppClip/Assets.xcassets/AppIcon.appiconset/Contents.json
Examples/AmplitudeSwiftUIExample/iOSAppClip/Assets.xcassets/Contents.json
Examples/AmplitudeSwiftUIExample/iOSAppClip/ContentView.swift
Examples/AmplitudeSwiftUIExample/iOSAppClip/Info.plist
Examples/AmplitudeSwiftUIExample/iOSAppClip/Preview Content/Preview Assets.xcassets/Contents.json
Examples/AmplitudeSwiftUIExample/iOSAppClip/iOSAppClip.entitlements
Examples/AmplitudeSwiftUIExample/iOSAppClip/iOSAppClipApp.swift
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/Assets.xcassets/AccentColor.colorset/Contents.json
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/Assets.xcassets/AppIcon.appiconset/Contents.json
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/Assets.xcassets/Contents.json
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/Assets.xcassets/WidgetBackground.colorset/Contents.json
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/Info.plist
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/iOSWidgetExample.intentdefinition
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/iOSWidgetExample.swift
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/iOSWidgetExampleBundle.swift
Examples/AmplitudeSwiftUIExample/iOSWidgetExample/iOSWidgetExampleLiveActivity.swift

- feat: add widget appclip examples
Add very basic examples for:
- iOS widget, it only [`Link`](https://developer.apple.com/documentation/widgetkit/creating-a-widget-extension) to the main app
- iOS AppClip, add amplitude send event flow

feat: add widget appclip examples

---

LICENSE

* Last fix had `chore:` prefix which didn't bump version on release
* Made minor update to License to make a new commit with `fix:`

fix: updated license to current year

---

Sources/Amplitude/Amplitude.swift
Tests/AmplitudeTests/AmplitudeTests.swift

* Add getUserId() and getDeviceId()
* https://amplitude.atlassian.net/browse/AMP-77096

fix: add getUserId() and getDeviceId() methods

---

Sources/Amplitude/Amplitude.swift
Tests/AmplitudeTests/AmplitudeSessionTests.swift

* added getSessionId() method
* updated tests

fix: added getSessionId() method

---

Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample.xcodeproj/project.pbxproj
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/TroubleShootingPlugin.swift
Sources/Amplitude/Amplitude.swift
Sources/Amplitude/Configuration.swift

chore: add TroubleShootingPlugin and making configuration accessible

---

Sources/Amplitude/Utilities/CodableExtension.swift
Tests/AmplitudeTests/Events/BaseEventTests.swift

Fix encoding Encodable values from [String: Any].
Missing "item_id" property and value in Amplitude Analytics for the code below
```swift
struct Item { 
let id: Int64
}
let item = Item(id: 10)
amplitude.track(eventType: "select_item", eventProperties: [
"itemId": item.id
])
```
* Does your PR have a breaking change?:  NO

fix: encoding Encodable values from [String: Any] (#82)

---

README.md

feat: Release 1.0.0
BREAKING CHANGE: New major version

feat: Release 1.0.0 \n\n BREAKING CHANGE: New major version

---

Sources/Amplitude/Utilities/OutputFileStream.swift
Tests/AmplitudeTests/Storages/PersistentStorageTests.swift

fix: storage instance issue

---

Sources/Amplitude/Utilities/HttpClient.swift

style: whitespace

---

Amplitude-Swift.xcodeproj/project.pbxproj
Sources/Amplitude/Amplitude.swift
Sources/Amplitude/Configuration.swift
Sources/Amplitude/Events/BaseEvent.swift
Sources/Amplitude/Storages/PersistentStorage.swift
Sources/Amplitude/Utilities/Diagonostics.swift
Sources/Amplitude/Utilities/DispatchQueueHolder.swift
Sources/Amplitude/Utilities/EventPipeline.swift
Sources/Amplitude/Utilities/HttpClient.swift
Sources/Amplitude/Utilities/OutputFileStream.swift
Sources/Amplitude/Utilities/UrlExtension.swift
Tests/AmplitudeTests/AmplitudeTests.swift
Tests/AmplitudeTests/Migration/StoragePrefixMigrationTests.swift
Tests/AmplitudeTests/Storages/PersistentStorageTests.swift
Tests/AmplitudeTests/Utilities/DiagnosticsTests.swift
Tests/AmplitudeTests/Utilities/EventPipelineTests.swift
Tests/AmplitudeTests/Utilities/HttpClientTests.swift
Tests/AmplitudeTests/Utilities/IdentifyInterceptorTests.swift
Tests/AmplitudeTests/Utilities/PersistentStorageResponseHandlerTests.swift

- migrate storage
- add diagnostics support

feat: migrate storage to for better thread safety

---

Sources/Amplitude/Plugins/Vendors/AppUtil.swift

Per the [docs](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtask) for beginBackgroundTask, "To extend the execution time of an app extension, use the [performExpiringActivity(withReason:using:)](https://developer.apple.com/documentation/foundation/processinfo/1617030-performexpiringactivity) method of [ProcessInfo](https://developer.apple.com/documentation/foundation/processinfo) instead." 
This should resolve some client issues flushing events from app extensions.

fix: Use appropriate background task API for app extensions

---

Sources/Amplitude/Utilities/HttpClient.swift

Conditionally compile code that requires the latest SDK, so we can support previous Xcode versions. Fixes #140 .

fix: Fix compilation on Xcode 14.x

---

Tests/AmplitudeTests/Supports/TestUtilities.swift
Tests/AmplitudeTests/Utilities/EventPipelineTests.swift

test: improve reliability of flaky test

---

Sources/Amplitude/Utilities/Diagonostics.swift
Tests/AmplitudeTests/Utilities/DiagnosticsTests.swift

Error logs are deduped and trimmed (keeping the 10 most recent logs).

fix: Trim and dedup error logs

---

Amplitude-Swift.xcodeproj/project.pbxproj
AmplitudeSwift.podspec
Package.swift

Bundle privacy manifest as part of resources for Cocoapods/SPM consumers.

chore: Add privacy manifest to SPM/Cocoapods

---

README.md

Bump version to `1.4.4` to include the changes in the previous commit https://github.com/amplitude/Amplitude-Swift/pull/150. It should have had `fix` rather than `chore`.
Specify the Flutter iOS plugin to use `Amplitude-Swift v1.4.4 and above` in https://github.com/amplitude/Amplitude-Flutter/pull/183/commits/de298db3bcfb46a01d06ce97e8625454b4dd2bcf.

fix: expose DET utils for flutter plugin

---

Sources/Amplitude/PrivacyInfo.xcprivacy

Update the "link to user" filed of "product interaction" to "Yes".

chore: product interaction should be linked to user

---

Sources/Amplitude/Plugins/ContextPlugin.swift
Sources/Amplitude/TrackingOptions.swift

Fix for https://github.com/amplitude/Amplitude-Swift/issues/166

refactor: make forCoppaControl a static function.

---

Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift
Tests/AmplitudeTests/AmplitudeIOSTests.swift

Apps that do not use a scene delegate (standard since iOS 13) will not send a `willEnterForeground` notification on initial launch. Instead, use the initial `didBecomeActive` notification.

fix: Send application opened for apps not yet using scene delegates

---

.swiftlint.yml

See discussion https://github.com/realm/SwiftLint/issues/5263#issuecomment-2115182747

chore: disable bad swiftlint rule

---

Sources/Amplitude/Storages/PersistentStorage.swift

Adds additional diagnostic logging

fix: Add additional diagnostic logging

---

Sources/Amplitude/Plugins/iOS/UIKitElementInteractions.swift
Tests/AmplitudeTests/Amplitude+Extensions.swift

This PR resolves compatibility issues between the SDK (which supports Swift 5.7) and newer Swift features used in some parts of the code. These changes ensure the SDK works correctly with older Xcode versions.

fix: Fix code compatibility issues on Xcode 14.1

---

Sources/Amplitude/Amplitude.swift
Sources/Amplitude/Configuration.swift
Sources/Amplitude/Plugins/BasePlugins.swift
Sources/Amplitude/Timeline.swift
Sources/Amplitude/Types.swift
Tests/AmplitudeTests/AmplitudeTests.swift

Adds various monitoring methods for plugins
* Does your PR have a breaking change?: No

feat: Enhancements to Plugin interface

---

Sources/Amplitude/ObjC/ObjCPlugin.swift
Tests/AmplitudeTests/Utilities/HttpClientTests.swift

chore: compatibility with new swiftlint version on github runner

---

Sources/Amplitude/Utilities/HttpClient.swift

Improves logging in http client

fix: improve logging in httpclient

---

Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift

Prevent main thread checker warning while accessing applicationState

fix: prevent main thread checker warning

---

Sources/Amplitude/Mediator.swift
Sources/Amplitude/Sessions.swift
Sources/Amplitude/State.swift

Improve multi-thread safety of array properties to prevent crash

fix: improve multi-thread safety to prevent crash

---

Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ContentView.swift
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/LocationPlugin.swift
Sources/Amplitude/Events/BaseEvent.swift
Sources/Amplitude/Events/EventOptions.swift
Sources/Amplitude/Events/Revenue.swift
Sources/Amplitude/ObjC/ObjCEventOptions.swift
Sources/Amplitude/ObjC/ObjCRevenue.swift
Tests/AmplitudeTests/Events/RevenueTests.swift

Adding ability to send revenue currency

fix: adding ability to send revenue currency

---

AmplitudeSwift.podspec

Add watchOS support back to CocoaPods

fix: add watchos support back to CocoaPods

---

Sources/Amplitude/Utilities/PersistentStorageResponseHandler.swift

fix: error handling for 400 request

---

Amplitude-Swift.xcodeproj/project.pbxproj
Package.swift
Package@swift-5.9.swift
Tests/AmplitudeTests/AmplitudeTests.swift
Tests/AmplitudeTests/Migration/LegacyDatabaseStorageTests.swift
Tests/AmplitudeTests/Migration/RemnantDataMigrationTests.swift

fixes running tests from spm package

fix: enable running tests from package.swift

---

Amplitude-Swift.xcodeproj/project.pbxproj
AmplitudeSwift.podspec
Cartfile
Package.swift
Package@swift-5.9.swift

Adds Core lib to Amplitude-Swift builds.

feat: Integrate AmplitudeCore

---

Examples/AmplitudeObjCExample/AmplitudeObjCExample/AppDelegate.m
Sources/Amplitude/Amplitude.swift
Sources/Amplitude/Constants.swift
Sources/Amplitude/Events/BaseEvent.swift
Sources/Amplitude/Identity.swift
Sources/Amplitude/Mediator.swift
Sources/Amplitude/ObjC/ObjCAmplitude.swift
Sources/Amplitude/Plugins/DestinationPlugin.swift
Sources/Amplitude/Sessions.swift
Sources/Amplitude/Timeline.swift
Sources/Amplitude/Types.swift

Adds AnalyticsClient conformance to Amplitude

feat: make amplitude conform to AnalyticsClient

---

Amplitude-Swift.xcodeproj/project.pbxproj
AmplitudeSwift.podspec
Cartfile
Examples/AmplitudeObjCExample/AmplitudeObjCExample/AppDelegate.m
Package.swift
Package@swift-5.9.swift
Sources/Amplitude/Amplitude.swift
Sources/Amplitude/Configuration.swift
Sources/Amplitude/ConsoleLogger.swift
Sources/Amplitude/Constants.swift
Sources/Amplitude/Events/BaseEvent.swift
Sources/Amplitude/Identity.swift
Sources/Amplitude/Mediator.swift
Sources/Amplitude/ObjC/ObjCAmplitude.swift
Sources/Amplitude/ObjC/ObjCAutocaptureOptions.swift
Sources/Amplitude/ObjC/ObjCLoggerProvider.swift
Sources/Amplitude/Plugins/DestinationPlugin.swift
Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift
Sources/Amplitude/Sessions.swift
Sources/Amplitude/Timeline.swift
Sources/Amplitude/Types.swift
Tests/AmplitudeTests/AmplitudeIOSTests.swift
Tests/AmplitudeTests/AmplitudeSessionTests.swift
Tests/AmplitudeTests/AmplitudeTests.swift
Tests/AmplitudeTests/AutocaptureRemoteConfigTests.swift
Tests/AmplitudeTests/Plugins/NetworkTrackingPluginTest.swift

Merges the (pre-reviewed) `unified_release` branch

feat: Unified SDK Release

---

Sources/Amplitude/Amplitude.swift

Fix issue: https://github.com/amplitude/Amplitude-Swift/issues/292

fix: fix amplitude remove and apply plugin

---

Amplitude-Swift.xcodeproj/project.pbxproj
AmplitudeSwift.podspec
Cartfile
Package.swift
Package@swift-5.9.swift

fix: update min core version

---

Sources/Amplitude/Plugins/iOS/UIKitElementInteractions.swift

Expand the supported range of gestures:
- RN uses custom gesture classes
- Ignore gestures like SessionReplayGesture by checking whether the view is a window.
- Expand the supported gesture range to all kinds of gestures

fix: add React Native gestures support for Element Interactions

---

Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift
Tests/AmplitudeTests/AmplitudeIOSTests.swift

Fix deadlock problem. Avoid calling storage.write on the main thread

fix: fix deadlock problem in app install event trigger

---

Sources/Amplitude/Sessions.swift

Enhance thread safety in Sessions

fix: Enhance thread safety in Sessions

---

Examples/AmplitudeObjCExample/AmplitudeObjCExample/AppDelegate.m
Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift
Sources/Amplitude/AutocaptureOptions.swift
Sources/Amplitude/Configuration.swift
Sources/Amplitude/InteractionsOptions.swift
Sources/Amplitude/ObjC/ObjCAutocaptureOptions.swift
Sources/Amplitude/ObjC/ObjCConfiguration.swift
Sources/Amplitude/ObjC/ObjCInteractionsOptions.swift
Sources/Amplitude/Utilities/MiscellaneousExtension.swift

fix: add spi frustration to autocapture frustration feature

---

Sources/Amplitude/Plugins/NetworkTrackingPlugin.swift
Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift
Sources/Amplitude/Utilities/DefaultEventUtils.swift

add appLifecycles remote config support

fix: add appLifecycles remote config support
