amplitude/Amplitude-Swift

Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample.xcodeproj/project.pbxproj, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ContentView.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/IDFACollectionPlugin.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/Info.plist, Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Events/EventOptions.swift, Sources/Amplitude/Plugins/ContextPlugin.swift, Sources/Amplitude/TrackingOptions.swift, Sources/Amplitude/Types.swift, Tests/AmplitudeTests/AmplitudeTests.swift
No.1 IDFA example
The value of idfa when using simulator is `00000000-0000-0000-0000-000000000000`.
1. in our backend, the idfa value will be always null. For privacy reasons, Amplitude processes the attribution information, but strips the values before saving the event in the system. We saved some hashed values into attribution_id instead.
2. idfa = `00000000-0000-0000-0000-000000000000` marked as invalid, so we need to manually replace this value with a valid one in order to test.
During the test, I test using breakpoint to check we do replace the event.idfa with the right value. The event stream also includes the attribution_id. 
No.2 idfv tracking option fix
No.3 locationInfoBlock tracking option implementation
=> feat: idfa plugin example

.github/workflows/lint.yml, .github/workflows/release.yml, .swiftlint.yml, AmplitudeSwift.podspec, README.md, Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Types.swift
- feat: add podspec and release flow
CocoaPods is working locally:
```
platform :ios, '16.0'
target 'cocoapod-test-app' do
pod 'AmplitudeSwift', :path => '/Users/marvin/src/amp/Amplitude-Swift'
end
```
=> feat: add podspec and release flow

.github/workflows/release.yml
- build: fix macos version in release workflow
`macos-latest` is macOS Big Sur 11: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners.
=> build: fix macos version in release workflow

.github/workflows/release.yml
- build: remove carthage and doc generation
We don't need to install dependency, so no need to have `Cartfile`, putting an empty `Cartfile` will get rid of the error though.
https://github.com/SwiftDocOrg/swift-doc is archived, I get rid of the doc generation now, it is not within current scope.
=> build: remove carthage and doc generation

.swiftpm/xcode/xcshareddata/xcschemes/Amplitude-Swift.xcscheme, AmplitudeSwift.podspec
- build: temp remove cocoapods watchos
1. Temporary disable watchos support due to: https://github.com/CocoaPods/CocoaPods/issues/11558. Unpaired watchos will cause failure, the fix of the above issue is merged but not released. I manually did https://github.com/CocoaPods/CocoaPods/issues/11558#issuecomment-1284573492 to fix my local `lint`. After the fix in Cocoapods is released, we can enable this back.
2. Add ".swiftpm/xcode/xcshareddata/xcschemes/Amplitude-Swift.xcscheme", the scheme is required by Carthage, but even after adding this and using a remote branch, I cannot make Carthage work. Probably related to: https://github.com/Carthage/Carthage/issues/2867. As this is also showing up in Xcode frequently, I just add it to git and commit it.
=> build: temp remove cocoapods watchos

.github/workflows/release.yml, .github/workflows/unit-test.yml, .gitignore, Amplitude-Swift.xcodeproj/Amplitude_SwiftTests_Info.plist, Amplitude-Swift.xcodeproj/Amplitude_Swift_Info.plist, Amplitude-Swift.xcodeproj/project.pbxproj, Amplitude-Swift.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Amplitude-Swift.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Amplitude-Swift.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, Amplitude-Swift.xcodeproj/xcshareddata/xcschemes/Amplitude-Swift-Package.xcscheme
- build: support carthage
In order to support Carthage, we need to have scheme in the xcode project:
1. use `swift package generate-xcodeproj` to generate the project (thank you @bgiori !)
2. remove driverkit in the target and add ios/ipad
=> build: support carthage

Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Plugins/AmplitudeDestinationPlugin.swift, Sources/Amplitude/Plugins/DestinationPlugin.swift
Current `DestinationPlugin` is a protocol, but it cannot hold the `timeline` property, so if user writes a new `DestinationPlugin`, needs to define a timeline as well, which shouldn't be needed.
To make it work, change `DestinationPlugin` to a class, and due to Swift's PWT (https://stackoverflow.com/a/44706021), we provide a common implementation for `setup` and `execute`, which can be override to call.
=> feat: update destination plugin to class

Sources/Amplitude/Configuration.swift
I fixed a small issue related to the EU server zone.
The code below doesn't work, because u still use **DEFAULT_API_HOST**
`
let amplitude = Amplitude(
Configuration(
apiKey: "YOUR-API-KEY",
serverZone: ServerZone.EU
)
)
`
You could double-check **HttpClient.getUrl()**. It always uses **configuration.serverUrl** if it's not empty. So the default **serverUrl** value should be empty to solve this issue.
Currently, I'm using your lib for EU server zone. And made a workaround from my side:
`
let amplitude = Amplitude(
Configuration(
apiKey: "YOUR-API-KEY",
serverZone: ServerZone.EU,
serverUrl: ""
)
)
`
=> fix: remove serverUrl as default value for configuration

Sources/Amplitude/Types.swift, Tests/AmplitudeTests/Events/BaseEventTests.swift
- fix: expose plan and ingestion metadata
Related to https://github.com/amplitude/Amplitude-Swift/issues/39
Tested with example app:
=> fix: expose plan and ingestion metadata

Sources/Amplitude/Plugins/Vendors/AppUtil.swift
The platform should show `iOS`, `tvOS`, etc. But now it's showing `iPhone 9,1`.
This pr fixed this issue and also fix the os_name to be consistent with the previous value.
=> fix: fix platform value

.github/workflows/semantic-pr.yml, Tests/AmplitudeTests/Events/BaseEventTests.swift, Tests/AmplitudeTests/Events/IdentifyTests.swift, Tests/AmplitudeTests/Events/RevenueTests.swift
* Ubuntu 18 is no longer supported in workflows, updated to 22.04 to fix Semantic PR check
=> chore: update semantic-pr to supported version 22.04

Sources/Amplitude/Utilities/IdentifyInterceptor.swift, Tests/AmplitudeTests/Events/BaseEventTests.swift, Tests/AmplitudeTests/Events/IdentifyTests.swift, Tests/AmplitudeTests/Events/RevenueTests.swift, Tests/AmplitudeTests/Utilities/IdentifyInterceptorTests.swift
Updated identify merging logic to ignore nil values.
=> fix: updated identify merging logic to ignore nil values

Sources/Amplitude/Plugins/ContextPlugin.swift
=> chore: do not use CTTelephonyNetworkInfo in simulator to hide annoying debug log messages with com.apple.commcenter.coretelephony.xpc mention

Sources/Amplitude/Events/EventOptions.swift
* made EventOptions.init public
=> fix: made EventOptions.init public

Sources/Amplitude/Events/BaseEvent.swift
Make `mergeEventOptions` public to use in Ampli codegen.
=> fix: make 'mergeEventOptions' public

Amplitude-Swift.xcodeproj/project.pbxproj, Amplitude-Swift.xcodeproj/xcshareddata/xcschemes/Amplitude-Swift-Package.xcscheme, Package.swift, Tests/AmplitudeTests/AmplitudeSessionTests.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/ConfigurationTests.swift, Tests/AmplitudeTests/ConsoleLoggerTests.swift, Tests/AmplitudeTests/Events/BaseEventTests.swift, Tests/AmplitudeTests/Events/GroupIdentifyEventTests.swift, Tests/AmplitudeTests/Events/IdentifyEventTests.swift, Tests/AmplitudeTests/Events/IdentifyTests.swift, Tests/AmplitudeTests/Events/RevenueEventTests.swift, Tests/AmplitudeTests/Events/RevenueTests.swift, Tests/AmplitudeTests/Migration/LegacyDatabaseStorageTests.swift, Tests/AmplitudeTests/Migration/RemnantDataMigrationTests.swift, Tests/AmplitudeTests/Migration/StoragePrefixMigrationTests.swift, Tests/AmplitudeTests/Storages/PersistentStorageTests.swift, Tests/AmplitudeTests/Supports/TestUtilities.swift, Tests/AmplitudeTests/TimelineTests.swift, Tests/AmplitudeTests/TypesTests.swift, Tests/AmplitudeTests/Utilities/EventPipelineTests.swift, Tests/AmplitudeTests/Utilities/HttpClientTests.swift, Tests/AmplitudeTests/Utilities/IdentifyInterceptorTests.swift, Tests/AmplitudeTests/Utilities/PersistentStorageResponseHandlerTests.swift, Tests/AmplitudeTests/Utilities/QueueTimeTests.swift, Tests/AmplitudeTests/Utilities/UrlExtensionTests.swift
Normalize package names for all package managers CocoaPods, Swift Package Manager (SPM), Carthage - now `import AmplitudeSwift` should be used instead of `import Amplitude_Swift`
* Does your PR have a breaking change?:   SPM and Carthage users need to update imports.
=> fix: normalize package names for all package managers

Sources/Amplitude/Amplitude.swift, Tests/AmplitudeTests/AmplitudeTests.swift
`seGroup()` should set `event.userProperties` similar to:
https://github.com/amplitude/Amplitude-iOS/blob/main/Sources/Amplitude/Amplitude.m#L1480
https://github.com/amplitude/Amplitude-Kotlin/blob/main/core/src/main/java/com/amplitude/core/Amplitude.kt#L311
=> fix: setGroup() should set event.userProperties

Sources/Amplitude/Events/BaseEvent.swift, Sources/Amplitude/Events/EventOptions.swift, Tests/AmplitudeTests/Events/BaseEventTests.swift
Moves `mergeEventOptions()` function to `EventOptions` class.
https://github.com/amplitude/javascript/pull/31001#discussion_r1290810390
=> fix: move mergeEventOptions() function to EventOptions class

Sources/Amplitude/Configuration.swift, Tests/AmplitudeTests/AmplitudeTests.swift
1. Normalize explicit empty instance name to be DEFAULT_INSTANCE.
2. Make 'read-only' some config values
* Does your PR have a breaking change?:  no (incorrect assignments to read-only config values should be removed)
=> fix: normalize explicit empty instance name

Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample.xcodeproj/project.pbxproj, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ContentView.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/IDFACollectionPlugin.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/LocationPlugin.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/TroubleShootingPlugin.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/Info.plist, Examples/AmplitudeSwiftUIExample/iOSAppClip/ContentView.swift, Examples/AmplitudeSwiftUIExample/iOSAppClip/iOSAppClipApp.swift, Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Constants.swift, Sources/Amplitude/Plugins/ContextPlugin.swift, Sources/Amplitude/TrackingOptions.swift, Sources/Amplitude/Types.swift, Tests/AmplitudeTests/AmplitudeTests.swift
https://amplitude.atlassian.net/browse/AMP-62860?focusedCommentId=204509
Goal keep Swift SDK interface the same as the other SDKs. Remove `locationInfoBlock`, provide Plugin example of setting location info instead.
1. Removed location-related code from SDK
2. Add an example plugin to collect location data (simplified `ios` version of `react-native-get-location` library)
* Does your PR have a breaking change?:  yes (location-specific code)
=> fix: remove location-related code from SDK, add an example plugin to collect location data

Sources/Amplitude/Plugins/DestinationPlugin.swift
Opens `DestinationPlugin.execute()` method to allow overriding in external modules.
=> fix: open 'DestinationPlugin.execute()' method

Amplitude-Swift.xcodeproj/project.pbxproj, AmplitudeSwift.podspec, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample.xcodeproj/project.pbxproj, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift, Package.swift, Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Constants.swift, Sources/Amplitude/Plugins/AnalyticsConnectorIdentityPlugin.swift, Sources/Amplitude/Plugins/AnalyticsConnectorPlugin.swift, Sources/Amplitude/Plugins/BasePlugins.swift, Sources/Amplitude/State.swift, Tests/AmplitudeTests/AmplitudeTests.swift
Support integration with experiment ios.
Based on [Amplitude-Kotlin](https://github.com/amplitude/Amplitude-Kotlin/pull/92/files#diff-6d55e2d5810c4d89bd2b78fdec680139ac4b867421ac08ccba98187023c52c6e) and Amplitude-iOS implementation.
Possible issue:
`DEFAULT_INSTANCE` name is `default_instance` in [Amplitude-Swift](https://github.com/amplitude/Amplitude-Swift/blob/main/Sources/Amplitude/Constants.swift#L58) and `$default_instance` in [experiment-ios-client](https://github.com/amplitude/experiment-ios-client/blob/main/Sources/Experiment/ExperimentConfig.swift#L82)
=> feat: support integration with experiment ios

Sources/Amplitude/Plugins/Vendors/AppUtil.swift, Sources/Amplitude/Plugins/Vendors/VendorSystem.swift, Sources/Amplitude/Utilities/HttpClient.swift
Based on example https://github.com/amplitude/Amplitude-Swift/pull/68.
Test environment: Simulator, fake server.
=> fix: mark uploads as background tasks to let them continue if the app enters the background

Examples/AmplitudeObjCExample/AmplitudeObjCExample/AppDelegate.m, Examples/AmplitudeObjCExample/AmplitudeObjCExampleTests/AmplitudeObjCExampleTests.m, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/TroubleShootingPlugin.swift, Sources/Amplitude/ObjC/ObjCPlugin.swift
1. Adds `flush()` support for destination plugins in Objective-C.
2. Fixes example TroubleShootingPlugin.
=> fix: Objective-C support for plugin flush()

Examples/AmplitudeObjCExample/AmplitudeObjCExampleTests/AmplitudeObjCExampleTests.m, Sources/Amplitude/Events/BaseEvent.swift, Sources/Amplitude/Events/EventOptions.swift, Sources/Amplitude/Events/Identify.swift, Sources/Amplitude/ObjC/ObjCBaseEvent.swift, Sources/Amplitude/ObjC/ObjCEventOptions.swift, Sources/Amplitude/ObjC/ObjCProperties.swift, Sources/Amplitude/ObjC/ObjCRevenue.swift
Adds support to get property values in Objective-C (required in unit tests).
=> fix: add Objective-C support to get property values

Sources/Amplitude/Utilities/CodableExtension.swift, Tests/AmplitudeTests/Events/BaseEventTests.swift
Add support for sending CGFloat values in event properties.
=> fix: add support for CGFloat property values

Sources/Amplitude/Amplitude.swift, Sources/Amplitude/ObjC/ObjCAmplitude.swift, Sources/Amplitude/Sessions.swift, Tests/AmplitudeTests/AmplitudeSessionTests.swift
Adds `setSessionId()` method.
Typical usage is `amplitude.setSessionId(timestamp: Int64(NSDate().timeIntervalSince1970 * 1000))`
Maybe it makes sense to add:
* method `startNewSession()` (without any parameters, the same as `setSessionId(timestamp: Int64(NSDate().timeIntervalSince1970 * 1000))`)
* method `endCurrentSession()` to end the current session but do not start new session. Can be used in client `Log Out` logic. Maybe it can be used inside SDK `reset()` method.
=> fix: add setSessionId() method

Sources/Amplitude/Utilities/HttpClient.swift, Tests/AmplitudeTests/Supports/TestUtilities.swift, Tests/AmplitudeTests/Utilities/HttpClientTests.swift
https://amplitude.atlassian.net/browse/AMP-87208
Adding `client_upload_time` so that when client-side clock is drifted, backend can [correct it](https://discourse.amplitude.com/t/is-it-possible-to-enable-event-time-adjustments-if-discrepancy-is-less-than-60-seconds/11627/5?u=justin)
=> feat: add client upload time

Amplitude-Swift.xcodeproj/project.pbxproj, Sources/Amplitude/PrivacyInfo.xcprivacy
https://amplitude.atlassian.net/browse/AMP-78469
iOS 17 requires this privacy manifest to list all data fields tracked. This PR only includes fields that are tracked by default. Customers should add more fields to their app's privacy manifest file if they decide to track more fields using Amplitude SDK. For example, by default the SDK tracks device Id only, but users can track user Id as well by `amplitude.setUserId()`. To do so, they have to add "User ID" `NSPrivacyCollectedDataTypeUserID` to `NSPrivacyCollectedDataType`. 
Please note that the definition of tracking is 
> Tracking refers to the act of linking user or device data collected from your app with user or device data collected from other companies' apps, websites, or offline properties for targeted advertising or advertising …
=> feat: add privacy manifest for ios 17

Sources/Amplitude/PrivacyInfo.xcprivacy
The SDK tracks coarse location (less than [3 decimal](https://support.garmin.com/en-CA/?faq=hRMBoCTy5a7HqVkxukhHd8)) by default by [IP address](https://www.if-so.com/geo-targeting/). Customers can use a [LocationPlugin](https://github.com/amplitude/Amplitude-Swift/blob/cf0ca474f50864fbaa5ea8ae7e70a58814456e61/Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/LocationPlugin.swift) to track latitude and longitude and add precise location to privacy manifest.
=> fix: should track coarse location by default

.gitignore, Amplitude-Swift.xcodeproj/project.pbxproj, Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Configuration.swift, Sources/Amplitude/Mediator.swift, Sources/Amplitude/ObjC/ObjCConfiguration.swift, Sources/Amplitude/ObjC/ObjCNetworkConnectivityCheckerPlugin.swift, Sources/Amplitude/Plugins/BasePlugins.swift, Sources/Amplitude/Plugins/NetworkConnectivityCheckerPlugin.swift, Sources/Amplitude/Types.swift, Sources/Amplitude/Utilities/EventPipeline.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/Plugins/NetworkConnectivityCheckerPluginTests.swift, Tests/AmplitudeTests/Supports/TestUtilities.swift, Tests/AmplitudeTests/Utilities/EventPipelineTests.swift, Tests/AmplitudeTests/Utilities/IdentifyInterceptorTests.swift
This feature is enabled by default. 
To opt out of using `NetworkConnectivityCheckerPlugin` and implement custom offline logic, setting `config.offline` to `NetworkConnectivityCheckerPlugin.Disabled` will prevent the plugin from installing. 
```
var testInstance = Amplitude(
configuration: Configuration(
apiKey: "API_KEY",
offline: NetworkConnectivityCheckerPlugin.Disabled
)
)
```
Tests to toggling network connection are based on https://amplitude.atlassian.net/wiki/spaces/GOV/pages/2319024851/Mock+network+changes.
Note that simulators don't accurately reflect network changes of Mac ([example](https://stackoverflow.com/questions/57223756/nwpathmonitor-not-calling-satisfied-in-swift)). So test it on a real device.
=> feat: add offline mode

Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Configuration.swift, Sources/Amplitude/Migration/StoragePrefixMigration.swift, Sources/Amplitude/Storages/PersistentStorage.swift, Sources/Amplitude/Types.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/ConfigurationTests.swift, Tests/AmplitudeTests/Supports/TestUtilities.swift
* Storage prefix now includes both **apiKey** and **instanceName** to prevent unintended data sharing
* Added migration to migrate legacy storage to new format
* Only migrate events in sandboxed apps to prevent data pollution across orgs
* Always migrate UserDefaults (deviceId, userId, etc) - these seem to be always sandboxed
* Added STORAGE_VERSION to UserDefaults to prevent duplicate migrations
* Added tests
=> fix: migrate storage to instanceName-apiKey to isolate by instance

Examples/AmplitudeObjCExample/AmplitudeObjCExampleTests/AmplitudeObjCExampleTests.m, Sources/Amplitude/Events/Identify.swift
- Same fix as in https://github.com/amplitude/Amplitude-Swift/pull/116 with unit test fix
=> fix: fix setOnce identify operation

Amplitude-Swift.xcodeproj/project.pbxproj, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample.xcodeproj/project.pbxproj, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ContentView.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/FilterPlugin.swift, Sources/Amplitude/Mediator.swift, Sources/Amplitude/Timeline.swift, Tests/AmplitudeTests/AmplitudeTests.swift
[Jira Ticket](https://amplitude.atlassian.net/browse/AMP-93216)
This is to fix the enrichment plugin that cannot  filter an event.
=> fix: fix the enrichment plugin to enable filter event

Sources/Amplitude/Amplitude.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/Migration/RemnantDataMigrationTests.swift
When sandboxing is not enabled for a mac app, do not migrate remnant data from the legacy iOS SDK
=> fix: Do not migrate remnant data from legacy SDK when sandboxing is not enabled

Sources/Amplitude/Amplitude.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/Supports/TestUtilities.swift
There's an edge case where we set the inForeground property to true before extending the session. If an event is triggered between this and the start session creating a new session, an old session can get extended.
Fixing this by only setting the inForeground property to true after a new session has been created if needed
=> fix: Set inForeground to true after a new session has been started

Sources/Amplitude/Plugins/ContextPlugin.swift, Tests/AmplitudeTests/AmplitudeTests.swift
Fix for https://github.com/amplitude/Amplitude-Swift/issues/107. Note that users that have an existing deviceID set from IDFV will maintain their current deviceID.
=> fix: Don't use idfv as deviceID if disabled

Sources/Amplitude/Utilities/HttpClient.swift
This is a slight performance improvement to initialise and use a single `DateFormatter` rather than recreating it whenever `getRequestData` is called. The initialization of `DateFormatter` can be quite constly on Apple platforms and should ideally be reused if the formatting is unchanged.
Here's an example screenshot we see from our Sentry performance logging:
=> perf: Use a single DateFormatter in HttpClient

Amplitude-Swift.xcodeproj/project.pbxproj, Sources/Amplitude/Plugins/iOS/UIKitScreenViews.swift, Tests/AmplitudeTests/Plugins/UIKitScreenViewsPluginTests.swift
- Use class name vs instance name of untitled view controllers for automatic screen tracking (#100)
- Resolve symlinks in paths before comparison (#121)
* Does your PR have a breaking change?: Yes, screen names will now be resolved properly
=> fix: Fixes for automatic screen tracking

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/unit-test.yml, Amplitude-Swift.xcodeproj/project.pbxproj, Sources/Amplitude/Events/BaseEvent.swift, Sources/Amplitude/Storages/PersistentStorage.swift, Sources/Amplitude/Utilities/HttpClient.swift, Tests/AmplitudeTests/AmplitudeTests.swift
This updated CI to run on the latest versions of MacOS/Xcode.
Running the tests locally with the latest Xcode results in a few failures, so I've fixed the following:
- Use sorted key output for JSON, as iOS 17+ uses a more secure dictionary type that randomizes key order
- Use strict URL parsing as the `URL(string:)` default behavior has changed in iOS 17
- Clean up testFilterAndEnrichmentPlugin results so that events aren't duplicated between runs (this does not appear to be an issue on CI, only while running locally). (@yuhao900914, can this test just use an in-memory store instead?)
=> fix: tests on iOS 17

Sources/Amplitude/Utilities/EventPipeline.swift, Tests/AmplitudeTests/Supports/TestUtilities.swift, Tests/AmplitudeTests/Utilities/EventPipelineTests.swift
EventPipeline previously cleared out tasks based on whether the http request was still in progress, not whether the request had fully completed and we had cleaned up the previous eventBlock. This means that a flush that was called after all requests had completed but before they were processed would re-upload previously uploaded events, as their backing files still exists.
Now, we track upload tasks more granularly by eventBlock URL, and clear them only when processing is complete, which guarantees that an eventBlock is only uploaded once (per amplitude instance, at least).
There is a change in behavior of how we upload with this change: instead of waiting for all requests to complete before starting a new batch, we will immediately start to upload any new eventBlocks on every flush, …
=> fix: Rely on on task completion vs http completion to end tasks

Amplitude-Swift.xcodeproj/project.pbxproj, Cartfile, Examples/AmplitudeObjCExample/AmplitudeObjCExample.xcodeproj/project.pbxproj
Carthage support has a few issues that need to be resolved:
- As of Carthage 0.37.0, Carthage will build all subprojects in a dependency, which means it includes our sample apps. Our ObjC sample app is currently broken on the latest versions of Xcode as you are no longer allowed to reference a package that is a direct ancestor of the project. I converted this to a direct project reference instead, and enabled emitting a module to keep the same semantics.
- analytics-connector-ios needs to be added as a dependency in a Cartfile, similar to https://github.com/amplitude/Amplitude-iOS/blob/main/Cartfile. This resolves #139 .
=> fix: better Carthage support

Tests/AmplitudeTests/Utilities/EventPipelineTests.swift
We were getting flushes in an unexpected order while running tests because our connectivity monitor was running, delaying requests until it detected a connection. This delay was compounded by the flush timer, which could fire other flush events during this delay.  Disable them both for EventPipeline tests.
Additionally, wait for a connection response vs just firing off a request in the simultaneous connection test to ensure it is completed before we attempt to clean up.
=> test: fix flaky tests on WatchOS

Amplitude-Swift.xcodeproj/project.pbxproj, Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift, Sources/Amplitude/Utilities/DefaultEventUtils.swift
https://amplitude.atlassian.net/browse/AMP-96756
Expose default event tracking utils so that they can be used in the Flutter iOS plugin.
- Create a class `DefaultEventUtils`
- Call `DefaultEventUtils. trackAppUpdatedInstalledEvent()` to track app updated & installed events 
=> chore: expose DET utils for flutter plugin

Sources/Amplitude/PrivacyInfo.xcprivacy
This PR declares the usage of [UserDefaults](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401) and reason of using it in the privacy manifest as we use it for [identity storage](https://github.com/amplitude/Amplitude-Swift/blob/891da3a2892df519a4ccf51a8442f8a5110623f0/Sources/Amplitude/Storages/PersistentStorage.swift#L22). 
[Segment](https://github.com/segmentio/analytics-swift/blob/7eeb2abf8452153af056baae5369679589f10936/Sources/Segment/Resources/PrivacyInfo.xcprivacy#L59C1-L68C10) declares it too.
=> chore: add required reason api to privacy manifest

Sources/Amplitude/PrivacyInfo.xcprivacy
> If you set NSPrivacyTracking to true then you need to provide at least one internet domain in NSPrivacyTrackingDomains; otherwise, you can provide zero or more domains.
This PR is from https://github.com/amplitude/amplitude-dev-center/pull/276#discussion_r1550220212. 
=> chore: delete tracking domains from privacy manifest

AmplitudeSwift.podspec
Use resource_bundle to prevent name conflicts with statically linked pods
=> fix: Adopt resource bundle for privacy manifest in Cocoapods

Amplitude-Swift.xcodeproj/project.pbxproj, Examples/AmplitudeObjCExample/AmplitudeObjCExample.xcodeproj/project.pbxproj, Examples/AmplitudeObjCExample/AmplitudeObjCExample.xcodeproj/xcshareddata/xcschemes/AmplitudeObjCExample.xcscheme, Examples/AmplitudeObjCExample/AmplitudeObjCExampleTests/AmplitudeObjCExampleTests.m, Examples/AmplitudeObjCExample/AmplitudeObjCExampleTests/TestAmplitude.swift, Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Plugins/ContextPlugin.swift, Sources/Amplitude/Plugins/NetworkConnectivityCheckerPlugin.swift, Sources/Amplitude/Sessions.swift, Sources/Amplitude/State.swift, Sources/Amplitude/Utilities/EventPipeline.swift, Sources/Amplitude/Utilities/HttpClient.swift, Tests/AmplitudeTests/Amplitude+Extensions.swift, Tests/AmplitudeTests/AmplitudeIOSTests.swift, Tests/AmplitudeTests/AmplitudeSessionTests.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/Storages/PersistentStorageTests.swift, Tests/AmplitudeTests/Supports/TestUtilities.swift, Tests/AmplitudeTests/TimelineTests.swift, Tests/AmplitudeTests/Utilities/IdentifyInterceptorTests.swift
Dispatch most public APIs and callbacks for timers and network calls to an internal queue to improve consistency. This also allows us to move work from the calling thread which is expected to be main for many view interactions. 
This comes with 2 behavioral changes:
- Any api call which generates an event no longer guarantees that the event would be recorded to disk when the call returns
- setSessionId no longer immediately sets the sessionId, and subsequent calls to getSessionId may return the previous sessionId until this completes.
=> feat: Dispatch operations to internal queue

Sources/Amplitude/Migration/RemnantDataMigration.swift, Sources/Amplitude/Plugins/AnalyticsConnectorPlugin.swift, Sources/Amplitude/Plugins/NetworkConnectivityCheckerPlugin.swift, Sources/Amplitude/Sessions.swift, Sources/Amplitude/Utilities/DefaultEventUtils.swift, Sources/Amplitude/Utilities/EventPipeline.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/Utilities/EventPipelineTests.swift
Fixes retain cycles internal to the Amplitude object, allowing it to correctly deallocate. (see https://github.com/amplitude/Amplitude-Swift/issues/44).
We also add a test ensuring that Amplitude will correctly deallocate to prevent this from happening in the future.
=> feat: Fix retain cycles in Amplitude so instance will not leak memory

Sources/Amplitude/Utilities/CodableExtension.swift
Support encoding of `UInt` as a value for event properties.
We, as users of the sdk, noticed our properties with UInt's got dropped. It worked in the old sdk at https://github.com/amplitude/Amplitude-iOS and in our opinion UInts should be supported since we and others use them extensively for IDs, counts, etc...
=> fix: support encoding UInt

Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift, Sources/Amplitude/Utilities/DefaultEventUtils.swift, Tests/AmplitudeTests/AmplitudeIOSTests.swift
Background tasks can launch an app without it ever being foregrounded, meaning our application opened event is not accurately being recorded. This mirrors changes in [Amplitude-iOS](https://github.com/amplitude/Amplitude-iOS/blob/bfdec453a31fd35942a619ef472fcf2f09e2313a/Sources/Amplitude/Amplitude.m#L458) that use application state to detect whether an app launch was from the background vs tracking didEnterForeground and didFinishLaunching notifications to infer background state.
=> fix: Improve application opened event reliability

Sources/Amplitude/Plugins/watchOS/WatchOSLifecycleMonitor.swift
Moves WKExtension to WKApplication to allow for compatibility with single-target watchOS applications. Single-target watchOS applications have been the default since Xcode 13.
=> feat: support single-target Watch applications

Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Plugins/Vendors/AppUtil.swift, Sources/Amplitude/Plugins/Vendors/VendorSystem.swift
Per Apple's [docs](https://developer.apple.com/documentation/technotes/tn3135-low-level-networking-on-watchos) on WatchOS, "... NWPathMonitor will remain in the .unsatisfied state.", meaning we will never attempt a connection once the connectivity checker runs. This is only blocked on a real device, and WatchOS 6-8 may still have inadvertently worked.
=> fix: Disable network connectivity check on watchOS as it is not supported on real devices

Sources/Amplitude/Plugins/AmplitudeDestinationPlugin.swift, Sources/Amplitude/Utilities/IdentifyInterceptor.swift, Tests/AmplitudeTests/Utilities/IdentifyInterceptorTests.swift
Dispatches IdentifyInterceptor's callback on the correct queue (vs main). 
=> fix: dispatch identify interceptor callbacks on correct queue

Sources/Amplitude/Plugins/watchOS/WatchOSLifecycleMonitor.swift
- Remove unused WKApplication reference
- Use app lifecycle notifications from WKExtension, not WKApplication, which are supported on WatchOS 18. (These should be equivalent as both notification rawValues are the same).
- Remove wasBackgrounded check, which did not appear to work properly as we were only tracking `didFinishLaunching` in the iOS lifecycle monitor.
=> fix: resolve compilation issue with watchOS 8.0

Sources/Amplitude/Plugins/ContextPlugin.swift
Fix for https://github.com/amplitude/Amplitude-Swift/issues/182
If we cannot retrieve a valid device id from the IDFV, fall back to using a generic uuid. This mirrors logic from the legacy SDK where the vendor id getter considers '00000000-0000-0000-0000-000000000000' as nil, but doesn't block an explicitly set id with the same value.
Note that clients who have already persisted an invalid deviceId will not be updated, and will need to either reset their amplitude instance, or set a new deviceId.
=> fix: Don't use idfv for deviceId if invalid

Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift
This PR fixes an indentation issue in the `IOSLifecycleMonitor.swift` file. No other code changes were made.
=> fix: fix indentation issues

Sources/Amplitude/Utilities/CodableExtension.swift, Tests/AmplitudeTests/Events/BaseEventTests.swift
This simple adding fixes converting dictionary which contains decimal value and passing through API.
We've faced with issue that decimal values were ignored on Amplitude console on this framework, but legacy framework works well.
=> fix: add support for Decimal property values

Amplitude-Swift.xcodeproj/project.pbxproj, Sources/Amplitude/Plugins/iOS/UIKitScreenViews.swift, Sources/Amplitude/Utilities/Weak.swift
Screen views will no longer fire if the topmost view controller is the same. This prevents an issue where embedded view controllers would mistakenly fire multiple events, as each would receive a call to viewDidAppear despite the top view controller being the same.
This also cleans up and improves thread safety for the UIKitScreenViews class.
=> Feat: dedup screen views

Sources/Amplitude/Plugins/iOS/UIKitUserInteractions.swift
Support only touchUpInside for UIButtons and valueChange for most.
=> fix: track touchupinside and valuechanged only

Sources/Amplitude/Constants.swift, Sources/Amplitude/Events/UserInteractionEvent.swift, Sources/Amplitude/Plugins/iOS/UIKitUserInteractions.swift, Tests/AmplitudeTests/Plugins/UIKitUserInteractionPluginTest.swift
This PR adds support to capture control events of the action methods fired.
=> feat: capture control events for autocapture

Sources/Amplitude/Plugins/iOS/UIKitElementInteractions.swift
This PR disables support for SwiftUI autocapture.
=> fix: disable swiftui support for autocapture

Sources/Amplitude/Configuration.swift, Sources/Amplitude/DefaultTrackingOptions.swift, Tests/AmplitudeTests/AutocaptureOptionsTests.swift, Tests/AmplitudeTests/ConfigurationTests.swift
This PR adds support back for tracking changes to `defaultTracking` options after `Configurations` initialization.
=> fix: track changes to defaultTracking after initialization

Sources/Amplitude/Utilities/PersistentStorageResponseHandler.swift, Tests/AmplitudeTests/Utilities/PersistentStorageResponseHandlerTests.swift
Delete events that are uploaded with a bad API key. They would previously be continuously unsuccessfully retried, and left orphaned on the device when the api key is finally changed.
=> fix: Delete events on an invalid api key response.

Sources/Amplitude/Plugins/iOS/UIKitElementInteractions.swift
This PR fixes the `UIScrollView.pinchGestureRecognizer` unavailability issue on tvOS.
=> fix: Fix UIScrollView pinchGestureRecognizer unavailability issue on tvOS

Sources/Amplitude/Utilities/EventPipeline.swift, Tests/AmplitudeTests/Utilities/EventPipelineTests.swift
Limits us to one simultaneous upload to limit the amount of memory we use. Flush completions are now fired when the current flush (if any) completes, not necessarily the flush that kicked them off.
=> fix: Send a max of one upload at a time

Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Configuration.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/Utilities/EventPipelineTests.swift
Adds a configuration parameter, `maxQueuedEventCount`, intended to control the maximum number of events we store on device. Set to a negative value to have no max count.
Every time we initialize Amplitude, we check `maxQueuedEventCount`. If set to a value greater than zero, we will delete all but the most recent maxQueuedEventCount events. Note that we will never attempt to split or otherwise rewrite a block during this process, so we may store an actual max event count of `maxQueuedEventCount + flushQueueSize - 1`. We also never will clear storage during the lifetime of the Amplitude instance, so more than maxQueuedEventCount events may be queued on the device until the next time Amplitude is run.
=> fix: Add maxQueuedEventCount parameter to trim events in storage if over a limit

Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Sessions.swift
`Amplitude.setSessionId` is not called on internal session id updates. move the observer to the actual backing variable.
=> fix: notify plugins of internal sessionId changes

Sources/Amplitude/Utilities/EventPipeline.swift
We're seeing memory growth consistent with delayed gc (a sawtooth pattern) from recent changes to how we upload files. Adding a release pool around the code fixes this memory growth.
=> fix: add autoreleasepool around sendNextEventFile

Amplitude-Swift.xcodeproj/project.pbxproj, Sources/Amplitude/Plugins/Vendors/AppUtil.swift, Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift
`UIApplication.shared` is not extension safe and will cause builds with `APPLICATION_EXTENSION_API_ONLY` to fail. This PR fixes access and adds `APPLICATION_EXTENSION_API_ONLY` to our build config so that our builds will fail as well.
=> fix: Use extension safe APIs

.github/workflows/release.yml, .github/workflows/unit-test.yml, Amplitude-Swift.xcodeproj/Amplitude_Swift_Info.plist, Amplitude-Swift.xcodeproj/project.pbxproj, Amplitude-Swift.xcodeproj/xcshareddata/xcschemes/Amplitude-Swift-Package-DisableUIKit.xcscheme, Cartfile, Package.swift, Sources/Amplitude/Plugins/Vendors/AppUtil.swift, Sources/Amplitude/Plugins/Vendors/VendorSystem.swift, Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift, Sources/Amplitude/Plugins/iOS/UIKitElementInteractions.swift, Sources/Amplitude/Plugins/iOS/UIKitScreenViews.swift, release.config.js, scripts/build_framework.sh
- Adds a new AMPLITUDE_DISABLE_UIKIT build option to disable UIKit portions of the codebase
- Adds a new scheme, "Amplitude-Swift-Package-DisableUIKit" that has this option preconfigured
- Links against analytics-connector-ios 1.2.3, which adds an xcframework based target
- Distributes binary frameworks as part of our releases, which can be picked up by Carthage.
=> feat: support building without UIKit

.github/workflows/release.yml
preserves symlinks vs copying file contents when zipping xcframeworks
=> fix: preserve symlinks when zipping xcframeworks

Package.swift
Reverts changes to Package.swift that opt into the new prepackaged framework based builds, meaning SPM customers will now build analytics-connector from source. The internal Xcode project will still point to the precompiled framework as it is used in Carthage builds. This should help customers with experiencing issues with https://github.com/amplitude/Amplitude-Swift/issues/238.
Note that the version rollback for analytics-connector is intentional, [the only changes we've made are related to packaging](https://github.com/amplitude/analytics-connector-ios/blob/main/CHANGELOG.md).
=> fix: restore Analytics-Connector to built from source version when distributing as a swift package

Sources/Amplitude/Utilities/CodableExtension.swift, Tests/AmplitudeTests/Events/BaseEventTests.swift
Fix for https://github.com/amplitude/Amplitude-Swift/issues/239.
Also attempts to clarify some of the logic by renaming some decode functions (which would usually operate on some nested container) to `asTypedFoo`, as they operate on the current container.
=> fix: properly decode embedded arrays

Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift, Sources/Amplitude/Utilities/DefaultEventUtils.swift, Tests/AmplitudeTests/AmplitudeIOSTests.swift
Fixes logic around app lifecycle tracking, to improve reliability of session, app opened, and app installed / updated events.
- If the app is already in the active state when the SDK is initialized, we will automatically fire app installed events and start a new session. This seems to be much closer to the expected behavior.
- App installed / updated events now only work with version numbers, not last event time, which may already be set by an event.
- Only send app install events once per instance name, in case we are re-initialized.
- Capture app delegate at time of use, not initialization, as it may not be set at the time we are initialized.
- Detects implicit scene configurations from info.plist, which will also opt in to willEnterForeground vs didBecomeActive for initial launch …
=> fix: improvements to app lifecycle monitoring

Sources/Amplitude/Utilities/HttpClient.swift
Considers NSURLErrorNotConnectedToInternet as another case to set the SDK into offline mode. We were seeing a lot of errors of this type retried. Would have expected NWPathMonitor to pick this up but seems there's some other case where this can still happen, and it probably belongs in this list too.
* Does your PR have a breaking change?: No
=> fix: also include NSURLErrorNotConnectedToInternet when setting configuration to offline

Examples/AmplitudeObjCExample/AmplitudeObjCExampleTests/TestAmplitude.swift, Sources/Amplitude/Types.swift, Sources/Amplitude/Utilities/EventPipeline.swift, Sources/Amplitude/Utilities/PersistentStorageResponseHandler.swift, Tests/AmplitudeTests/Supports/TestUtilities.swift, Tests/AmplitudeTests/Utilities/EventPipelineTests.swift, Tests/AmplitudeTests/Utilities/PersistentStorageResponseHandlerTests.swift
fix: prevent high-frequency requests on continuing failing by:
- add repeat interval on EventPipeline
- add max retry limit
=> fix: add repeat interval on EventPipeline to prevent high frequency requests on continuing failing

Tests/AmplitudeTests/Utilities/EventPipelineTests.swift
try to fix likely-to-fail test case
=> fix: fix likely to fail test case

Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Utilities/Atomic.swift, Sources/Amplitude/Utilities/Diagonostics.swift, Sources/Amplitude/Utilities/HttpClient.swift, Tests/AmplitudeTests/Storages/PersistentStorageTests.swift, Tests/AmplitudeTests/Utilities/DiagnosticsTests.swift
Enhance thread safety
- Add locks to lazy vars in Amplitude
Lazy variables are not thread-safe. They may be initialized multiple times if accessed in multiple threads.
- Add a lock to protect Diagnostics collection properties
They are accessed on multiple threads. Considering the low access frequency, use one lock to keep it simple.
=> fix: enhance thread safety of properties

Sources/Amplitude/Utilities/EventPipeline.swift, Sources/Amplitude/Utilities/HttpClient.swift
Offline the SDK directly after receiving a Bad URL error.
=> fix: offline directly after receive bad url error

Sources/Amplitude/ObjC/ObjCAmplitude.swift
Allow Swift Plugins to be added to the objc version of the SDK. We relax the types here and throw a runtime error as Plugin is currently unrepresentable in ObjC.
Alternatively, we could create some sort of wrapper object, basically the inverse of `ObjCPluginWrapper`.
=> fix: allow adding Swift Plugins to ObjC Amplitude

Sources/Amplitude/Constants.swift, Sources/Amplitude/Utilities/EventPipeline.swift, Sources/Amplitude/Utilities/PersistentStorageResponseHandler.swift, Tests/AmplitudeTests/AmplitudeTests.swift, Tests/AmplitudeTests/Utilities/EventPipelineTests.swift
1. Found an unused `flushMaxRetries` parameter in Configuration, which is suitable as a retry cap for EventPipeline.
2. The previous PR’s handling of 400 errors by dropping events was based on the idea that the user manually set the 400, which can be considered an unrecoverable error. In such cases, dropping events is acceptable. However, the customer pointed out another scenario where a 400 error is returned due to VPN configuration region issues, which may be corrected at some point. Based on this assumption, it is best not to discard the events.
=> fix: port Configuration.flushMaxRetries as pipeline retry cap

Sources/Amplitude/Amplitude.swift
Removes targetQueue/qos specifier from trackingQueue.
I've set up the following test harness to run multiple amplitude instances at once:
```
let amplitude1 = Amplitude(configuration: Configuration(apiKey: "aaa", instanceName: "instance-1"))
let amplitude2 = Amplitude(configuration: Configuration(apiKey: "aaa", instanceName: "instance-2"))
let trackingQueue = DispatchQueue(label: "App Tracking Queue", attributes: .concurrent)
func sendIdentify(amplitude: Amplitude) {
trackingQueue.async {
amplitude.identify(userProperties: ["a": "b"])
sendIdentify(amplitude: amplitude)
}
}
func sendEvent(amplitude: Amplitude) {
trackingQueue.async {
amplitude.track(eventType: "aaa")
sendEvent(amplitude: amplitude)
}
}
sendIdentify(amplitude: amplitude1)
sendEvent(amplitude: amplitude1) …
```
=> fix: potential priority inversion for storagequeue access

Sources/Amplitude/Events/Identify.swift, Sources/Amplitude/Identity.swift
Applies user properties in the same order as our backend.
=> fix: apply identifies to identity userProperties in correct order

Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift, Sources/Amplitude/Plugins/iOS/UIKitElementInteractions.swift, Sources/Amplitude/Plugins/iOS/UIKitScreenViews.swift
explicitly unregisters amplitude as a listener when lifecycle monitor is removed
=> fix: clean up ios observers on stop

Sources/Amplitude/Identity.swift, Tests/AmplitudeTests/IdentityTests.swift
treat non-op user properties as sets
=> fix: treat non-op user properties as sets

Sources/Amplitude/Configuration.swift
Moves config defaults to a new defaults structure so they can be shared in more places
=> fix: move default init properties to new defaults structure so they can be shared

Sources/Amplitude/Configuration.swift
removes unused enableRemoteConfig option
* Does your PR have a breaking change?:  yes but never released
=> fix: remove unused enableRemoteConfig option

Amplitude-Swift.xcodeproj/project.pbxproj, Examples/AmplitudeObjCExample/AmplitudeObjCExample/AppDelegate.h, Examples/AmplitudeObjCExample/AmplitudeObjCExample/AppDelegate.m, Examples/AmplitudeObjCExample/AmplitudeObjCExample/ViewController.h, Examples/AmplitudeObjCExample/AmplitudeObjCExample/ViewController.m, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/AmplitudeSwiftUIExampleApp.swift, Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ContentView.swift, Sources/Amplitude/ObjC/ObjCAutocaptureOptions.swift, Sources/Amplitude/ObjC/ObjCConfiguration.swift, Sources/Amplitude/ObjC/ObjCNetworkTrackingOptions.swift
add ObjC interface for NetworkTrackingOptions
=> feat: add ObjC interface for NetworkTrackingOptions

Amplitude-Swift.xcodeproj/project.pbxproj, Sources/Amplitude/Configuration.swift, Sources/Amplitude/ConsoleLogger.swift, Sources/Amplitude/Constants.swift, Sources/Amplitude/ObjC/ObjCAutocaptureOptions.swift, Sources/Amplitude/ObjC/ObjCLoggerProvider.swift, Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift, Sources/Amplitude/Sessions.swift, Tests/AmplitudeTests/AmplitudeIOSTests.swift, Tests/AmplitudeTests/AmplitudeSessionTests.swift, Tests/AmplitudeTests/AutocaptureRemoteConfigTests.swift, Tests/AmplitudeTests/Plugins/NetworkTrackingPluginTest.swift
Adds auto capture remote config for analyticsSDK.iosSDK namespace. We still need backend APIs to power this.
This changes the behavior of autocapture such that changes committed after amplitude init are ignored.
* [x Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-SDK-Template/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
=> feat: wire up remote config for autocapture

Sources/Amplitude/Amplitude.swift, Tests/AmplitudeTests/AmplitudeSessionTests.swift
With the changes to identify, some session events did not have the correct device / session id set, which would get filtered by our destination plugin on validity check.
This adds the correct device / user ids where needed, and updates the tests to verify user and device id for session events.
=> fix: set user/device id on session events

Amplitude-Swift.xcodeproj/project.pbxproj, AmplitudeSwift.podspec, Cartfile, Package.swift, Package@swift-5.9.swift, Sources/Amplitude/Amplitude.swift, Tests/AmplitudeTests/AmplitudeTests.swift
adds support for plugin lookup by type, recently added in core.
=> fix: implement plugin lookup by type

Sources/Amplitude/Constants.swift
Fix the name of the `Network Request` event to be consistent with the public documentation.
=> fix: name of network request event

Sources/Amplitude/Amplitude.swift, Sources/Amplitude/Plugins/Vendors/AppUtil.swift, Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift, Tests/AmplitudeTests/AmplitudeIOSTests.swift
When Amplitude is initialized after the app is in the foreground, we will immediately try to fire app opened/ app installed / session start events as we will not get a subsequent onEnterForeground. We recently enhanced the consistency of the user/device id set on an event, so that these automatically tracked events will no longer pick up changes from userid/deviceId set immediately after Amplitude initialization.
To restore this ability, we now fire the events on the tracking queue. This effectively adds enough of a delay that identity can be set immediately after init and be picked up by the events.
During testing, I found that the tracking queue could actually start while still in init - we also now pause the queue to ensure we are fully set up.
In the tests:
The previous tests that …
=> fix: delay app start / end events when starting amplitude in foreground

Sources/Amplitude/Utilities/QueueTimer.swift, Tests/AmplitudeTests/Utilities/TimeIntervalExtensionsTests.swift
- fix `TimeInterval` unit conversion helpers
- add unit tests for `TimeInterval` helpers
- remove unused `hours` and `days` helpers
- `swift test` *(fails: Failed to clone repository https://github.com/amplitude/AmplitudeCore-Swift.git: Failed to connect to proxy port 8080)*
=> fix: TimeInterval helpers

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/unit-test.yml, Tests/AmplitudeTests/Storages/PersistentStorageTests.swift
Use Xcode 16.1 to generate artifacts as 16 is now min in the App Store (https://developer.apple.com/news/upcoming-requirements/?id=02212025a)
=> fix: update to xcode 16.1 for prebuilt artifacts
